[project]
name = "14-http-compress-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "loguru>=0.7.3",
    "requests>=2.32.3",
    "typer>=0.15.1",
]

[tool.ruff]
# Set the maximum line length to 80
# line-length = 80

# ignore = [
#   "T201", # Allow use of print statements
# ]

select = ["ALL"]
