[project]
name = "misc_projects"
version = "0.1.0"
description = "Simple Python projects for getting up to speed with Python."
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "aiofiles>=25.1.0",
    "aiohttp>=3.13.3",
    "requests>=2.32.5",
    "rich>=14.3.1",
]

[tool.ruff.lint]

ignore = [
  "S101", # Allow assert statements
  "T201", # Allow print statements
  "T203", # Allow pprint statements
]

select = ["ALL"]
