[project]
name = "misc_projects"
version = "0.1.0"
description = "Simple Python projects for getting up to speed with Python."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "requests>=2.32.5",
]

[tool.ruff.lint]

ignore = [
  "S101", # Allow assert statements
  "T201", # Allow print statements
  "T203", # Allow pprint statements
]

select = ["ALL"]
