[project]
name = "e16-virtual-list-even-nums-proxy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[tool.ruff]
# Set the maximum line length to 80
# line-length = 80

ignore = [
  "PLR2004", # Allow constants
  "S101",    # Allow assert
  "T201",    # Allow use of print statements
]

select = ["ALL"]
