# OpenAPI schema document for Orders API

# Step 4: Referencing the models in the #/components/paths section

openapi: 3.1.0

info:
  title: Orders API
  version: 0.1.0
  description: API for managing life cycle of customer orders.

servers:
  - url: http://localhost:5000
    description: Local development server

paths:
  /orders/:
    get:
      summary: Get a list of all orders
      operationId: readOrders
      parameters:
        - name: cancelled
          in: query
          description: Filter orders by cancellation status
          required: false
          schema:
            type: boolean
        - name: limit
          in: query
          description: Limit the number of orders returned
          required: false
          schema:
            type: integer
            default: null
      responses:
        "200":
          description: A list of orders
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetOrdersSchema"

    post:
      summary: Create a new order
      operationId: createOrder
      requestBody:
        description: Order details to create a new order
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateOrderSchema"
      responses:
        "201":
          description: Order created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetOrderSchema"

  /orders/{order_id}:
    parameters:
      - name: order_id
        in: path
        description: Unique identifier for the order
        required: true
        schema:
          type: string
          format: uuid
    get:
      summary: Get details of a specific order
      operationId: readOrder
      responses:
        "200":
          description: Order details retrieved successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetOrderSchema"


    put:
      summary: Update an existing order
      operationId: updateOrder
      requestBody:
        description: Updated order details
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateOrderSchema"
      responses:
        "200":
          description: Order updated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetOrderSchema"

    delete:
      summary: Delete an order
      operationId: deleteOrder
      responses:
        "204":
          description: Order deleted successfully

  /orders/{order_id}/cancel:
    parameters:
      - name: order_id
        in: path
        description: Unique identifier for the order
        required: true
        schema:
          type: string
          format: uuid
    post:
      summary: Cancel an order
      operationId: cancelOrder
      responses:
        "200":
          description: Order cancelled successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetOrderSchema"
  /orders/{order_id}/pay:
    parameters:
      - name: order_id
        in: path
        description: Unique identifier for the order
        required: true
        schema:
          type: string
          format: uuid
    post:
      summary: Pay for an order
      operationId: payOrder
      responses:
        "200":
          description: Order paid successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetOrderSchema"

components:
  schemas:
    OrderItemSchema:
      description: Schema for an item in an order
      type: object
      properties:
        product:
          type: string
          description: Name of the product
          required: true
        size:
          type: string
          description: Size of the product (e.g., small, medium, large)
          enum: [small, medium, large]
          required: true
        quantity:
          type: integer
          description: Quantity of the product ordered
          required: false
          minimum: 1
          default: 1
    CreateOrderSchema:
      description: Schema for creating a new order
      type: object
      properties:
        order:
          type: array
          description: List of items in the order
          items:
            $ref: '#/components/schemas/OrderItemSchema'
          required: true
          minItems: 1
    GetOrderSchema:
      description: Schema for retrieving order details
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Unique identifier for the order
          required: true
        created:
          type: string
          format: date-time
          description: Timestamp when the order was created
          required: true
        status:
          type: string
          description: Current status of the order (e.g., pending, paid, cancelled)
          enum:
            - created
            - progress
            - cancelled
            - dispatched
            - delivered
          required: true
        order:
          type: array
          description: List of items in the order
          items:
            $ref: '#/components/schemas/OrderItemSchema'
          required: true
          minItems: 1
    GetOrdersSchema:
      description: Schema for retrieving a list of orders
      type: object
      properties:
        orders:
          type: array
          items:
            $ref: '#/components/schemas/GetOrderSchema'
          description: List of orders
          required: true
