[tool.poetry]
name = "orders"
version = "0.1.0"
description = ""
authors = ["Sergio F. Gonzalez <sergio.f.gonzalez@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
uvicorn = "^0.26.0"
fastapi = "^0.109.0"
pyyaml = "^6.0.1"


[tool.poetry.group.dev.dependencies]
httpie = "^3.2.2"


[tool.poetry.group.test.dependencies]
dredd-hooks = "^0.2.0"
schemathesis = "^3.24.3"
requests = "^2.31.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
