[project]
name = "013_find_duplicate_files"
version = "0.1.0"
description = "Lab 013: Find duplicate files in a directory tree."
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[dependency-groups]
dev = [
  "pytest>=9.0.2",
  "ruff>=0.14.8",
  "pytest-cov>=7.0.0",
  "pytest-sugar>=1.1.1",
]

[tool.ruff]

ignore = [
  "T201", # Allow print statements
]

# Enable all rules
select = ["ALL"]

# Specific per-file-ignores for the tests directory
per-file-ignores = { "tests/**/*.py" = ["S101"] } # Allow assert in tests

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.pytest.ini_options]
addopts = "--verbosity=3 --cov --cov-report=html"
pythonpath = ["."]

[tool.coverage.run]
# source = ["./*"]
omit = ["tests/*"]
