[tool.poetry]
name = "orders"
version = "0.1.0"
description = ""
authors = ["Sergio F. Gonzalez <sergio.f.gonzalez@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
uvicorn = "^0.28.0"
fastapi = "^0.110.0"
pyyaml = "^6.0.1"
sqlalchemy = "^2.0.28"


[tool.poetry.group.dev.dependencies]
httpie = "^3.2.2"
alembic = "^1.13.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
