version: "3.9"

services:
  database:
    image: postgres:14.2
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - database-data:/var/lib/postgresql/data

  api:
    build:
      context: .
      args:
        - APP_PACKAGE_NAME=orders
    ports:
      - 8080:8080
    depends_on:
      - database
    environment:
      - DB_URL=postgresql://postgres:postgres@database:5432/postgres

volumes:
  database-data:
