[tool.poetry]
name = "cryptid"
version = "0.1.0"
description = ""
authors = ["Sergio F. Gonzalez <sergio.f.gonzalez@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.109.2"
uvicorn = "^0.27.0.post1"
python-jose = {extras = ["cryptography"], version = "^3.3.0"}
passlib = "^1.7.4"
python-multipart = "^0.0.9"
jinja2 = "^3.1.3"


[tool.poetry.group.dev.dependencies]
httpie = "^3.2.2"
pytest = "^8.0.0"
httpx = "^0.27.0"
schemathesis = "^3.25.6"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
