openapi: 3.0.3

info:
  title: Kitchen API
  description: >
    API that allows to manage the production of orders in the kitchen for the
    CoffeeMesh application.
  version: 0.1.0

servers:
  - url: http://localhost:5000
    description: local development server
  - url: https://coffeemesh.com
    description: Main production server
  - url: https://coffeemesh-staging.com
    description: staging server for testing purposes only

paths:
  /kitchen/schedules:
    get:
      operationId: getScheduledOrders
      summary:
        Retrieves a list of orders that has been scheduled for production.
      tags:
        - kitchen

    post:
      operationId: createScheduledOrder
      summary:
        Schedules an order for production in the kitchen.
      tags:
        - kitchen

  /kitchen/schedules/{schedule_id}:
    parameters:
      - in: path
        name: schedule_id
        required: true
        schema:
          type: string
          format: uuid

    get:
      operationId: getScheduledOrder
      summary: Returns the status and details of a specific scheduled order.
      tags:
        - kitchen

    put:
      operationId: updateScheduledOrder
      summary: Replaces an existing schedule.
      tags:
        - kitchen

    delete:
      operationId: deleteSchedule
      summary: Removes an existing scheduled order.
      tags:
        - kitchen

  /kitchen/schedules/{schedule_id}/status:
    parameters:
      - in: path
        name: schedule_id
        required: true
        schema:
          type: string
          format: uuid

    get:
      operationId: getScheduledOrderStatus
      summary: Returns the status of a specific scheduled order.
      tags:
        - kitchen


  /kitchen/schedules/{schedule_id}/cancel:
    parameters:
      - in: path
        name: schedule_id
        required: true
        schema:
          type: string
          format: uuid

    post:
      operationId: cancelSchedule
      summary: Cancels a specific scheduled order.
      tags:
        - kitchen

components:
  responses:
    NotFound:
      description: The specified resource was not found.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"


  schemas:
    Error:
      type: object
      properties:
        detail:
          oneOf:
            - type: string
            - type: array
      required:
        - detail
      additionalProperties: false

    OrderItemSchema:
      type: object
      # required:
      #   - product
      #   - size
      # properties:
      #   product:
      #     type: string
      #   size:
      #     type: string
      #     enum:
      #       - small
      #       - medium
      #       - big
      #   quantity:
      #     type: integer
      #     format: int64
      #     default: 1
      #     minimum: 1
      #     maximum: 1000000
      # additionalProperties: false

    ScheduleOrderSchema:
      type: object
      # required:
      #   - order
      # properties:
      #   order:
      #     type: array
      #     minItems: 1
      #     items:
      #       $ref : "#/components/schemas/OrderItemSchema"
      # additionalProperties: false

    GetScheduledOrderSchema:
      # additionalProperties: false
      # type: object
      # required:
      #   - id
      #   - created
      #   - status
      #   - order
      # properties:
      #   id:
      #     type: string
      #     format: uuid
      #   created:
      #     type: string
      #     format: date-time
      #   status:
      #     type: string
      #     enum:
      #       - created
      #       - paid
      #       - progress
      #       - cancelled
      #       - dispatched
      #       - delivered
      #   order:
      #     type: array
      #     minItems: 1
      #     items:
      #       $ref: "#/components/schemas/OrderItemSchema"

