[project]
name = "30-cannonball-3d-plot"
version = "0.1.0"
description = "simple program to plot cannonball trajectories"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.9.2",
]
